### ISSUE TITLE
1D, 2D, 3D and 4D modes

### ISSUE THREAD

**Issue by EntityinArray** [haseebahmed295/Noise-Nodes#1]
It seems that your noise nodes are hardcoded to output 3D textures. It would be cool if there was an option to select between 1D, 2D, 3D and 4D textures, the same way you can do with vanilla Blender's Noise Texture
![image](https://github.com/user-attachments/assets/36e18952-9760-4ab1-8065-8de994bcc0e5)

**Comment by haseebahmed295** [comment]
this feature is added in v.3 .
